version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - summary-network
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - summary-network
networks:
  summary-network:
